//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhatchaWatchin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medium
    {
        //public int Id { get; set; }
        public string Title { get; set; }
        public string Plot { get; set; }
        public string Poster { get; set; }
        public string Genre { get; set; }
        public string Year { get; set; }
        public string Type { get; set; }
        public string Runtime { get; set; }
        public string Language { get; set; }
        public string MPAARating { get; set; }
        public Nullable<decimal> IMDBRating { get; set; }
        public string Website { get; set; }
        public string imdbID { get; set; }

        public Medium()
        {

        }

        public Medium(string title, string plot, string poster, string genre, string year, string type, string mpaaRating, string runtime, string language, decimal imdbRating, string website, string imdbID)
        {
            this.Title = title;
            this.Plot = plot;
            this.Poster = poster;
            this.Genre = genre;
            this.Year = year;
            this.Type = type;
            this.MPAARating = mpaaRating;
            this.Runtime = runtime;
            this.Language = language;
            this.IMDBRating = imdbRating;
            this.Website = website;
            this.imdbID = imdbID;

        }



    }
}
